version: '2'
services:
  spark-master:
    image: spark-master-etg:latest
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "8888:8888"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
      - ./data:/data