version: '2'
services:
  spark-worker-1:
    image: spark-worker-etg:latest
    container_name: spark-worker
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
      - ./data:/data